<?php
require __DIR__.'/includes/bootstrap.php';$admin=music_require_admin($mysqli);
$settings=[];$result=$mysqli->query("SELECT setting_key,setting_value FROM music_ai_settings WHERE setting_key LIKE 'daily_agent_%'");while($row=$result->fetch_assoc())$settings[$row['setting_key']]=$row['setting_value'];
$worker=$mysqli->query("SELECT * FROM music_ai_workers ORDER BY heartbeat_at DESC LIMIT 1")->fetch_assoc();$health=json_decode((string)($worker['health_json']??''),true)?:[];
$queue=$mysqli->query("SELECT status,COUNT(*) total FROM music_ai_jobs GROUP BY status");$queueCounts=[];while($row=$queue->fetch_assoc())$queueCounts[$row['status']]=(int)$row['total'];
$active=$mysqli->query("SELECT r.*,t.title,t.genre,t.current_stage track_stage,t.progress_percent track_progress,j.attempts job_attempts,j.next_attempt_at FROM music_ai_agent_runs r LEFT JOIN music_ai_tracks t ON t.id=r.track_id LEFT JOIN music_ai_jobs j ON j.agent_run_id=r.id AND j.status IN ('PENDING','PROCESSING') WHERE r.status IN ('QUEUED','RUNNING','RECOVERING') ORDER BY r.id DESC LIMIT 1")->fetch_assoc();
$runs=[];$rows=$mysqli->query("SELECT r.*,t.title,t.genre,t.is_published,j.attempts job_attempts,j.next_attempt_at FROM music_ai_agent_runs r LEFT JOIN music_ai_tracks t ON t.id=r.track_id LEFT JOIN music_ai_jobs j ON j.agent_run_id=r.id ORDER BY r.id DESC LIMIT 50");while($row=$rows->fetch_assoc())$runs[]=$row;
$heartbeatAge=$worker?time()-strtotime($worker['heartbeat_at']):null;$workerOnline=$worker&&$worker['status']!=='STOPPED'&&$heartbeatAge<max(120,(int)music_setting($mysqli,'worker_timeout_minutes','20')*60);
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>eMusic Lite • Agente musical</title><link rel="stylesheet" href="assets/css/style.css"></head><body class="app-body"><div class="app"><aside class="sidebar"><div class="logo">eMusic Lite</div><nav><a href="dashboard.php">Início</a><a href="criar-musica.php">Criar com IA</a><a href="minhas-musicas.php">Minhas músicas</a><a class="active" href="ai-agent.php">Agente musical</a></nav><a class="logout" href="logout.php">Sair</a></aside>
<main class="main"><header class="topbar"><div><h1>Agente musical</h1><p>Operação editorial persistente e independente do navegador.</p></div><div class="agent-buttons"><button id="createAgentTrack">Criar música agora</button><?php if($active&&in_array($active['status'],['RECOVERING','FAILED'],true)):?><button class="secondary" id="resumeAgent" data-run="<?=(int)$active['id']?>">Retomar agora</button><?php endif;?></div></header><div id="agentMessage" class="alert" hidden></div>
<section class="health-grid"><div class="health-card"><span>Worker</span><strong class="<?= $workerOnline?'online':'offline' ?>"><?= $workerOnline?'Online':'Offline' ?></strong><small><?= $worker?'Heartbeat '.music_e(date('d/m/Y H:i:s',strtotime($worker['heartbeat_at']))):'Sem heartbeat' ?></small></div><div class="health-card"><span>Texto</span><strong class="<?= !empty($health['text_online'])?'online':'offline' ?>"><?= !empty($health['text_online'])?'Online':'Offline' ?></strong><small><?=!empty($health['text_model_available'])?'Modelo disponível':'Modelo não confirmado'?></small></div><div class="health-card"><span>Gerador musical</span><strong class="<?= !empty($health['music_online'])?'online':'offline' ?>"><?= !empty($health['music_online'])?'Online':'Offline' ?></strong><small><?=!empty($health['music_configured'])?'Configurado':'Aguardando inventário'?></small></div><div class="health-card"><span>ComfyUI</span><strong class="<?= !empty($health['comfy_online'])?'online':'offline' ?>"><?= !empty($health['comfy_online'])?'Online':'Offline' ?></strong><small>Fila existente tem prioridade</small></div></section>
<section class="panel"><div class="panel-header"><div><h2>Execução atual</h2><p><?=($queueCounts['PENDING']??0)?> pendente(s) · <?=($queueCounts['PROCESSING']??0)?> em processamento</p></div></div><?php if($active):?><div class="current-run"><h3><?=music_e($active['title']??'Planejando título')?></h3><p><?=music_e($active['track_stage']??$active['current_stage'])?></p><div class="real-progress"><div style="width:<?=(int)($active['track_progress']??$active['progress_percent'])?>%"></div></div><div class="run-facts"><span>Tentativas: <?=(int)($active['job_attempts']??$active['attempts'])?></span><span>Recuperações: <?=(int)$active['recoveries']?></span><span>Próxima tentativa: <?= $active['next_attempt_at']?music_e(date('d/m/Y H:i:s',strtotime($active['next_attempt_at']))):'—' ?></span></div><?php if($active['error_message']):?><p class="agent-error">Falha temporária registrada; consulte os logs do servidor para detalhes técnicos.</p><?php endif;?></div><?php else:?><p>Nenhuma execução editorial ativa.</p><?php endif;?></section>
<section class="panel"><h2>Preferências editoriais</h2><form id="agentSettings" class="form-grid"><div class="field"><label>Geração diária</label><select name="settings[daily_agent_enabled]"><option value="1" <?=($settings['daily_agent_enabled']??'1')==='1'?'selected':''?>>Ativada</option><option value="0" <?=($settings['daily_agent_enabled']??'1')==='0'?'selected':''?>>Desativada</option></select></div><div class="field"><label>Horário diário</label><input type="time" name="settings[daily_agent_time]" value="<?=music_e($settings['daily_agent_time']??'04:30')?>" required></div><div class="field"><label>Duração (segundos)</label><input type="number" min="30" max="600" name="settings[daily_agent_duration_seconds]" value="<?=(int)($settings['daily_agent_duration_seconds']??180)?>"></div><div class="field"><label>Publicação automática</label><select name="settings[daily_agent_auto_publish]"><option value="1" <?=($settings['daily_agent_auto_publish']??'1')==='1'?'selected':''?>>Ativada após validação</option><option value="0" <?=($settings['daily_agent_auto_publish']??'1')==='0'?'selected':''?>>Manter privada</option></select></div><div class="field full"><label>Gêneros permitidos (separados por vírgula)</label><input name="settings[daily_agent_genres]" maxlength="1000" value="<?=music_e($settings['daily_agent_genres']??'Pop,MPB,Eletrônica,Jazz,Lo-fi')?>"></div><div class="field full"><label>Tipos permitidos</label><select name="settings[daily_agent_composition_types]"><option value="INSTRUMENTAL,VOCAL" <?=($settings['daily_agent_composition_types']??'')==='INSTRUMENTAL,VOCAL'?'selected':''?>>Instrumental e vocal</option><option value="INSTRUMENTAL" <?=($settings['daily_agent_composition_types']??'')==='INSTRUMENTAL'?'selected':''?>>Somente instrumental</option><option value="VOCAL" <?=($settings['daily_agent_composition_types']??'')==='VOCAL'?'selected':''?>>Somente vocal</option></select></div><input type="hidden" name="csrf_token" value="<?=music_e(music_csrf_token())?>"><button>Salvar preferências</button></form></section>
<section class="panel"><h2>Histórico</h2><div class="table-wrap"><table class="agent-table"><thead><tr><th>Execução</th><th>Música</th><th>Etapa</th><th>Tentativas</th><th>Próxima tentativa</th><th>Criada em</th><th>Ação</th></tr></thead><tbody><?php if(!$runs):?><tr><td colspan="7">Nenhuma execução.</td></tr><?php endif;?><?php foreach($runs as $run):?><tr><td><?=music_e($run['trigger_type'])?><small><?=music_e($run['status'])?></small></td><td><?=music_e($run['title']??'Planejando')?><small><?=music_e($run['genre']??'')?></small></td><td><?=music_e($run['current_stage'])?> · <?=(int)$run['progress_percent']?>%<?php if($run['error_message']):?><small class="agent-error">Erro técnico resumido disponível no job</small><?php endif;?></td><td><?=(int)($run['job_attempts']??$run['attempts'])?> / <?=(int)$run['recoveries']?> rec.</td><td><?=$run['next_attempt_at']?music_e(date('d/m/Y H:i',strtotime($run['next_attempt_at']))):'—'?></td><td><?=music_e(date('d/m/Y H:i',strtotime($run['created_at'])))?></td><td><?php if(in_array($run['status'],['RECOVERING','FAILED'],true)):?><button type="button" class="secondary resume-run" data-run="<?=(int)$run['id']?>">Retomar agora</button><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section></main></div>
<script>window.MUSIC_CSRF=<?=json_encode(music_csrf_token())?>;</script><script src="assets/js/music-agent.js"></script></body></html>
