<?php
require __DIR__.'/includes/bootstrap.php';$user=music_require_page_user($mysqli);
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>eMusic Lite • Criar música</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-body"><div class="app"><aside class="sidebar"><div class="logo">eMusic Lite</div><nav><a href="dashboard.php">Início</a><a class="active" href="criar-musica.php">Criar com IA</a><a href="minhas-musicas.php">Minhas músicas</a><?php if(music_is_admin((int)$user['id'])):?><a href="ai-agent.php">Agente musical</a><?php endif;?></nav><a class="logout" href="logout.php">Sair</a></aside>
<main class="main"><header class="topbar"><div><h1>Crie sua música</h1><p>Conte a ideia; o trabalho pesado será processado no servidor.</p></div></header><div id="formMessage" class="alert" hidden></div>
<section class="panel"><form id="createMusicForm" class="form-grid">
<div class="field full"><label for="original_idea">Ideia original</label><textarea id="original_idea" name="original_idea" rows="5" minlength="20" maxlength="8000" required placeholder="Descreva a história, sensação e evolução da música sem citar artistas ou obras existentes."></textarea></div>
<div class="field"><label for="genre">Gênero</label><input id="genre" name="genre" maxlength="120" required placeholder="Ex.: MPB"></div><div class="field"><label for="subgenre">Subgênero</label><input id="subgenre" name="subgenre" maxlength="120" placeholder="Ex.: folk acústico"></div>
<div class="field"><label for="mood">Clima</label><input id="mood" name="mood" maxlength="120" required placeholder="Ex.: esperançoso"></div><div class="field"><label for="theme">Tema</label><input id="theme" name="theme" maxlength="255" required placeholder="Ex.: recomeços"></div>
<div class="field"><label for="composition_type">Composição</label><select id="composition_type" name="composition_type"><option value="INSTRUMENTAL">Instrumental</option><option value="VOCAL">Com voz</option></select></div><div class="field"><label for="language">Idioma</label><select id="language" name="language"><option>Português</option><option>Inglês</option><option>Espanhol</option><option>Francês</option><option>Italiano</option><option>Alemão</option><option>Sem idioma</option></select></div>
<div class="field"><label for="desired_duration_seconds">Duração desejada</label><select id="desired_duration_seconds" name="desired_duration_seconds"><option value="60">1 minuto</option><option value="120">2 minutos</option><option value="180" selected>3 minutos</option></select><small>O gerador atual suporta músicas de até 3 minutos.</small></div><div class="field"><label for="bpm">BPM opcional</label><input id="bpm" name="bpm" type="number" min="40" max="240" placeholder="Ex.: 92"></div>
<div class="field"><label for="voice_type">Tipo de voz opcional</label><input id="voice_type" name="voice_type" maxlength="120" placeholder="Ex.: voz suave e grave"></div><div class="field"><label for="instruments">Instrumentos desejados</label><input id="instruments" name="instruments" maxlength="3000" placeholder="Ex.: violão, baixo, percussão"></div>
<div class="field full"><label for="descriptive_references">Referências descritivas</label><textarea id="descriptive_references" name="descriptive_references" rows="3" maxlength="3000" placeholder="Descreva textura, época, arranjo ou produção. Não informe nomes de artistas ou músicas."></textarea></div>
<input type="hidden" name="csrf_token" value="<?=music_e(music_csrf_token())?>"><button type="submit">Criar projeto</button></form></section></main></div>
<script>window.MUSIC_CSRF=<?=json_encode(music_csrf_token())?>;</script><script src="assets/js/music-create.js"></script></body></html>
