<?php
require __DIR__.'/includes/bootstrap.php';$user=music_require_page_user($mysqli);
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>eMusic Lite • Comparar modelos</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-body"><div class="app"><aside class="sidebar"><div class="logo">eMusic Lite</div><nav><a href="dashboard.php">Início</a><a href="criar-musica.php">Criar com IA</a><a class="active" href="criar-musica2.php">Comparar modelos</a><a href="minhas-musicas.php">Minhas músicas</a><?php if(music_is_admin((int)$user['id'])):?><a href="ai-agent.php">Agente musical</a><?php endif;?></nav><a class="logout" href="logout.php">Sair</a></aside>
<main class="main"><header class="topbar"><div><h1>Comparar modelos</h1><p>Esta página usa sempre a mesma música-base. Troque apenas o modelo para comparar a saída.</p></div></header><div id="formMessage" class="alert" hidden></div>
<section class="panel"><form id="createMusicForm" class="form-grid">
<div class="field full"><label for="original_idea">Ideia original</label><textarea id="original_idea" name="original_idea" rows="5" minlength="20" maxlength="8000" required>Instrumental eletrônico cinematográfico e moderno, começando com uma atmosfera espacial suave e misteriosa. Aos poucos entram pulsos rítmicos, baixo sintetizado profundo e bateria eletrônica precisa. A música deve crescer gradualmente, ganhar energia no meio e chegar a um clímax amplo e emocionante, mantendo melodia memorável, sensação futurista e produção limpa. Depois do clímax, reduzir a intensidade e terminar com uma resolução elegante e atmosférica.</textarea></div>
<div class="field"><label for="genre">Gênero</label><input id="genre" name="genre" maxlength="120" required value="Eletrônica"></div><div class="field"><label for="subgenre">Subgênero</label><input id="subgenre" name="subgenre" maxlength="120" value="Cinemática eletrônica"></div>
<div class="field"><label for="mood">Clima</label><input id="mood" name="mood" maxlength="120" required value="Futurista, épico e inspirador"></div><div class="field"><label for="theme">Tema</label><input id="theme" name="theme" maxlength="255" required value="Descoberta, tecnologia e evolução"></div>
<div class="field"><label for="composition_type">Composição</label><select id="composition_type" name="composition_type"><option value="INSTRUMENTAL" selected>Instrumental</option></select></div><div class="field"><label for="language">Idioma</label><select id="language" name="language"><option selected>Sem idioma</option></select></div>
<div class="field"><label for="generation_model">Modelo de geração</label><select id="generation_model" name="generation_model"><option value="turbo" selected>Equilibrado — ACE-Step Turbo</option><option value="shift1">Mais detalhes — ACE-Step Shift1</option><option value="shift3">Timbre mais limpo — ACE-Step Shift3</option><option value="xl_sft">Qualidade máxima — ACE-Step XL SFT 4B (experimental)</option><option value="stable_audio">Stable Audio Open — CPU (experimental)</option></select><small>Troque somente este campo. Os dois modos experimentais usam sample de 30 segundos.</small></div><div class="field"><label for="desired_duration_seconds">Duração desejada</label><select id="desired_duration_seconds" name="desired_duration_seconds"><option value="30">30 segundos</option><option value="60" selected>1 minuto</option></select></div>
<div class="field"><label for="bpm">BPM</label><input id="bpm" name="bpm" type="number" min="40" max="240" value="118" readonly></div><div class="field"><label for="voice_type">Tipo de voz</label><input id="voice_type" name="voice_type" value="" readonly placeholder="Instrumental"></div><div class="field"><label for="instruments">Instrumentos desejados</label><input id="instruments" name="instruments" maxlength="3000" value="sintetizadores analógicos, pads atmosféricos, baixo eletrônico profundo, bateria eletrônica, arpejadores, piano processado"></div>
<div class="field full"><label for="descriptive_references">Referências descritivas</label><textarea id="descriptive_references" name="descriptive_references" rows="3" maxlength="3000">Produção moderna e ampla, estéreo bem definido, graves firmes sem excesso, transientes claros, texturas espaciais, progressão dinâmica evidente, introdução atmosférica, seção central energética, clímax cinematográfico e encerramento suave. Evitar voz, fala, canto e samples vocais.</textarea></div>
<input type="hidden" name="csrf_token" value="<?=music_e(music_csrf_token())?>"><button type="submit">Criar teste com este modelo</button></form></section></main></div>
<script>window.MUSIC_CSRF=<?=json_encode(music_csrf_token())?>;</script><script src="assets/js/music-create.js"></script></body></html>
