<?php
require __DIR__.'/includes/bootstrap.php';$user=music_require_page_user($mysqli);
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>eMusic Lite • Funk carioca</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-body"><div class="app"><aside class="sidebar"><div class="logo">eMusic Lite</div><nav><a href="dashboard.php">Início</a><a href="criar-musica.php">Criar com IA</a><a href="criar-musica2.php">Comparar modelos</a><a href="musica3.php">Sertanejo teste</a><a class="active" href="musica4.php">Funk carioca teste</a><a href="minhas-musicas.php">Minhas músicas</a><?php if(music_is_admin((int)$user['id'])):?><a href="ai-agent.php">Agente musical</a><?php endif;?></nav><a class="logout" href="logout.php">Sair</a></aside>
<main class="main"><header class="topbar"><div><h1>Funk carioca brasileiro</h1><p>Preset fixo para comparar os modelos usando sempre a mesma música.</p></div></header><div id="formMessage" class="alert" hidden></div>
<section class="panel"><form id="createMusicForm" class="form-grid">
<div class="field full"><label for="original_idea">Ideia original</label><textarea id="original_idea" name="original_idea" rows="6" minlength="20" maxlength="8000" required>Instrumental de funk carioca brasileiro moderno, dançante e de alta energia, com grave forte, kick seco, caixa estalada e percussão sincopada característica. Criar uma introdução curta e impactante, seguida por uma base rítmica contagiante com subgrave profundo e elementos eletrônicos minimalistas. Alternar trechos mais vazios com quedas de impacto e retornos fortes da batida. O refrão instrumental deve ser imediatamente reconhecível, repetitivo na medida certa e feito para pista e sistemas de som grandes. A produção deve soar brasileira, urbana e atual, sem copiar nenhuma faixa existente. Finalizar com uma última virada e corte seco.</textarea></div>
<div class="field"><label for="genre">Gênero</label><input id="genre" name="genre" maxlength="120" required value="Funk brasileiro"></div><div class="field"><label for="subgenre">Subgênero</label><input id="subgenre" name="subgenre" maxlength="120" value="Funk carioca"></div>
<div class="field"><label for="mood">Clima</label><input id="mood" name="mood" maxlength="120" required value="Energético, urbano e dançante"></div><div class="field"><label for="theme">Tema</label><input id="theme" name="theme" maxlength="255" required value="Baile, cidade, noite e energia de pista"></div>
<div class="field"><label for="composition_type">Composição</label><select id="composition_type" name="composition_type"><option value="INSTRUMENTAL" selected>Instrumental</option></select></div><div class="field"><label for="language">Idioma</label><select id="language" name="language"><option selected>Sem idioma</option></select></div>
<div class="field"><label for="generation_model">Modelo de geração</label><select id="generation_model" name="generation_model"><option value="studio_midi">Studio Real — MIDI + samples reais</option><option value="turbo" selected>Equilibrado — ACE-Step Turbo</option><option value="shift1">Mais detalhes — ACE-Step Shift1</option><option value="shift3">Timbre mais limpo — ACE-Step Shift3</option><option value="xl_sft">Qualidade máxima — ACE-Step XL SFT 4B (experimental)</option><option value="stable_audio">Stable Audio Open — CPU (experimental)</option></select><small>Studio Real prioriza instrumentos sampleados; para funk eletrônico o ACE-Step pode continuar mais adequado. XL SFT e Stable Audio usam 30 segundos.</small></div><div class="field"><label for="desired_duration_seconds">Duração desejada</label><select id="desired_duration_seconds" name="desired_duration_seconds"><option value="30">30 segundos</option><option value="60" selected>1 minuto</option><option value="120">2 minutos</option><option value="180">3 minutos</option></select></div>
<div class="field"><label for="bpm">BPM</label><input id="bpm" name="bpm" type="number" min="40" max="240" value="132" readonly></div><div class="field"><label for="voice_type">Tipo de voz</label><input id="voice_type" name="voice_type" value="" readonly placeholder="Instrumental"></div><div class="field"><label for="instruments">Instrumentos desejados</label><input id="instruments" name="instruments" maxlength="3000" value="subgrave 808, kick seco, caixa estalada, tamborzão eletrônico, hi-hats, percussão sincopada, sintetizadores curtos, efeitos de transição"></div>
<div class="field full"><label for="descriptive_references">Referências descritivas</label><textarea id="descriptive_references" name="descriptive_references" rows="4" maxlength="3000">Produção brasileira de funk carioca contemporâneo, subgrave muito presente mas controlado, bateria seca e frontal, espaços de silêncio estratégicos, viradas curtas, impacto de pista, estéreo limpo e poucos elementos melódicos para manter foco no groove. Evitar voz, fala, canto, gritos e samples vocais. Não imitar artistas ou músicas existentes.</textarea></div>
<input type="hidden" name="csrf_token" value="<?=music_e(music_csrf_token())?>"><button type="submit">Criar funk com este modelo</button></form></section></main></div>
<script>window.MUSIC_CSRF=<?=json_encode(music_csrf_token())?>;</script><script src="assets/js/music-create.js"></script></body></html>
