<?php
require __DIR__.'/includes/bootstrap.php';$user=music_require_page_user($mysqli);
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>eMusic Lite • Sertanejo universitário</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="app-body"><div class="app"><aside class="sidebar"><div class="logo">eMusic Lite</div><nav><a href="dashboard.php">Início</a><a href="criar-musica.php">Criar com IA</a><a href="criar-musica2.php">Comparar modelos</a><a class="active" href="musica3.php">Sertanejo teste</a><a href="minhas-musicas.php">Minhas músicas</a><?php if(music_is_admin((int)$user['id'])):?><a href="ai-agent.php">Agente musical</a><?php endif;?></nav><a class="logout" href="logout.php">Sair</a></aside>
<main class="main"><header class="topbar"><div><h1>Sertanejo universitário brasileiro</h1><p>Preset fixo para comparar os modelos usando sempre a mesma música.</p></div></header><div id="formMessage" class="alert" hidden></div>
<section class="panel"><form id="createMusicForm" class="form-grid">
<div class="field full"><label for="original_idea">Ideia original</label><textarea id="original_idea" name="original_idea" rows="6" minlength="20" maxlength="8000" required>Instrumental de sertanejo universitário brasileiro contemporâneo, romântico e animado, com introdução marcante de violão e guitarra limpa. A base deve ter levada sertaneja moderna, baixo firme, bateria acústica bem definida e sanfona entrando em frases melódicas curtas. Construir versos com dinâmica moderada e um refrão instrumental grande, fácil de memorizar, emotivo e com sensação de show ao vivo. A produção deve soar brasileira, popular, atual e radiofônica, sem copiar nenhuma música existente. Encerrar com repetição do tema principal e final claro.</textarea></div>
<div class="field"><label for="genre">Gênero</label><input id="genre" name="genre" maxlength="120" required value="Sertanejo"></div><div class="field"><label for="subgenre">Subgênero</label><input id="subgenre" name="subgenre" maxlength="120" value="Sertanejo universitário brasileiro"></div>
<div class="field"><label for="mood">Clima</label><input id="mood" name="mood" maxlength="120" required value="Romântico, alegre e envolvente"></div><div class="field"><label for="theme">Tema</label><input id="theme" name="theme" maxlength="255" required value="Paixão, encontro e noite de festa"></div>
<div class="field"><label for="composition_type">Composição</label><select id="composition_type" name="composition_type"><option value="INSTRUMENTAL" selected>Instrumental</option></select></div><div class="field"><label for="language">Idioma</label><select id="language" name="language"><option selected>Sem idioma</option></select></div>
<div class="field"><label for="generation_model">Modelo de geração</label><select id="generation_model" name="generation_model"><option value="turbo" selected>Equilibrado — ACE-Step Turbo</option><option value="shift1">Mais detalhes — ACE-Step Shift1</option><option value="shift3">Timbre mais limpo — ACE-Step Shift3</option><option value="xl_sft">Qualidade máxima — ACE-Step XL SFT 4B (experimental)</option><option value="stable_audio">Stable Audio Open — CPU (experimental)</option></select><small>XL SFT e Stable Audio mudam automaticamente a duração para 30 segundos.</small></div><div class="field"><label for="desired_duration_seconds">Duração desejada</label><select id="desired_duration_seconds" name="desired_duration_seconds"><option value="30">30 segundos</option><option value="60" selected>1 minuto</option></select></div>
<div class="field"><label for="bpm">BPM</label><input id="bpm" name="bpm" type="number" min="40" max="240" value="126" readonly></div><div class="field"><label for="voice_type">Tipo de voz</label><input id="voice_type" name="voice_type" value="" readonly placeholder="Instrumental"></div><div class="field"><label for="instruments">Instrumentos desejados</label><input id="instruments" name="instruments" maxlength="3000" value="violão de aço acústico natural, guitarra limpa, sanfona acústica, baixo elétrico de cordas, bateria acústica real, percussão leve"></div>
<div class="field full"><label for="descriptive_references">Referências descritivas</label><textarea id="descriptive_references" name="descriptive_references" rows="4" maxlength="3000">Produção brasileira contemporânea de sertanejo universitário, instrumentos acústicos com ataque natural, ressonância de madeira, palhetada humana, bateria acústica gravada em estúdio, baixo elétrico de cordas e sanfona acústica. Evitar timbres de sintetizador, pads, instrumentos MIDI artificiais, voz, fala, canto, coral e samples vocais. Não imitar artistas ou músicas existentes.</textarea></div>
<input type="hidden" name="csrf_token" value="<?=music_e(music_csrf_token())?>"><button type="submit">Criar sertanejo com este modelo</button></form></section></main></div>
<script>window.MUSIC_CSRF=<?=json_encode(music_csrf_token())?>;</script><script src="assets/js/music-create.js"></script></body></html>
