CREATE DATABASE IF NOT EXISTS emusic_lite CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE emusic_lite;

CREATE TABLE IF NOT EXISTS tracks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  artist VARCHAR(200) NOT NULL,
  genre VARCHAR(120) NOT NULL,
  mood VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  duration VARCHAR(20) NOT NULL,
  cover_url VARCHAR(500) NOT NULL,
  stream_url VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
