#!/usr/bin/env php
<?php
if(PHP_SAPI!=='cli')exit(1);
putenv('MUSIC_AUTH_SUBJECT_KEY=test-only-subject-key');
require __DIR__.'/../includes/bootstrap.php';require_once __DIR__.'/../services/TrackService.php';require_once __DIR__.'/../services/ModerationService.php';require_once __DIR__.'/../services/DailyMusicAgentService.php';
$passed=0;$failed=0;function check(bool $condition,string $label):void{global $passed,$failed;if($condition){echo"[OK] {$label}\n";$passed++;}else{echo"[FALHA] {$label}\n";$failed++;}}
$moderator=new ModerationService();$blocked=false;try{$moderator->validate(['idea'=>'Copie a letra de uma música existente']);}catch(MusicPermanentException $e){$blocked=true;}check($blocked,'Moderação bloqueia pedido explícito de cópia');
$blocked=false;try{$moderator->validate(['idea'=>'Faça no estilo de Artista Famoso']);}catch(MusicPermanentException $e){$blocked=true;}check($blocked,'Referência de imitação de artista é bloqueada');
try{
  $mysqli->begin_transaction();
  $a=hash('sha256','test-owner-a-'.random_bytes(8));$b=hash('sha256','test-owner-b-'.random_bytes(8));$nameA='Teste A';$nameB='Teste B';
  $stmt=$mysqli->prepare("INSERT INTO music_ai_users(external_subject_hash,display_name,user_type,status)VALUES(?,?,'CUSTOMER','ACTIVE')");$stmt->bind_param('ss',$a,$nameA);$stmt->execute();$ownerA=(int)$stmt->insert_id;$stmt->bind_param('ss',$b,$nameB);$stmt->execute();$ownerB=(int)$stmt->insert_id;$stmt->close();
  $input=['genre'=>'MPB','subgenre'=>'Folk','mood'=>'Calmo','theme'=>'Recomeço','language'=>'Português','composition_type'=>'VOCAL','desired_duration_seconds'=>120,'bpm'=>90,'voice_type'=>'Voz suave','instruments'=>'Violão e baixo','descriptive_references'=>'Arranjo acústico original','original_idea'=>'Uma canção original sobre encontrar um novo caminho ao amanhecer.'];
  $service=new TrackService($mysqli);$trackId=$service->create($ownerA,$input);
  $stmt=$mysqli->prepare('SELECT id FROM music_ai_tracks WHERE id=? AND owner_user_id=?');$stmt->bind_param('ii',$trackId,$ownerA);$stmt->execute();check((bool)$stmt->get_result()->fetch_assoc(),'Dono acessa o próprio projeto');$stmt->close();
  $stmt=$mysqli->prepare('SELECT id FROM music_ai_tracks WHERE id=? AND owner_user_id=?');$stmt->bind_param('ii',$trackId,$ownerB);$stmt->execute();check(!$stmt->get_result()->fetch_assoc(),'Troca de ID não concede propriedade');$stmt->close();
  $queue=new QueueService($mysqli);$jobA=$queue->enqueue($ownerA,$trackId,'test:idempotent:'.$trackId);$jobB=$queue->enqueue($ownerA,$trackId,'test:idempotent:'.$trackId);check($jobA===$jobB,'Operation key impede job duplicado');
  $simulateCrash=function(string $checkpoint)use($mysqli,$queue,$jobA):void{$mysqli->query("UPDATE music_ai_jobs SET status='PROCESSING',locked_by='crashed-test',started_at=DATE_SUB(NOW(),INTERVAL 30 MINUTE),heartbeat_at=DATE_SUB(NOW(),INTERVAL 30 MINUTE),attempts=1 WHERE id=".(int)$jobA);check($queue->recoverStale(5)>=1,"Queda após {$checkpoint} recupera o job");};
  $simulateCrash('project_created_at');
  $plan=['title'=>'Amanhã de Papel','description'=>'Canção original de teste','genre'=>'MPB','subgenre'=>'Folk','mood'=>'Calmo','bpm'=>90,'key'=>'C maior','duration_seconds'=>120,'structure'=>[['name'=>'Intro','start_seconds'=>0,'end_seconds'=>12]],'instruments'=>['violão','baixo'],'lyrical_concept'=>'Recomeço','lyrics'=>'A manhã inventa caminhos novos','audio_prompt'=>'Original acoustic song, no artist references','cover_prompt'=>'Original abstract sunrise cover, no text'];
  $service->savePlan($trackId,$plan);$simulateCrash('plan_saved_at');
  $service->saveLyrics($trackId,'Recomeço',$plan['lyrics'],'Português',false);$simulateCrash('lyrics_saved_at');
  $service->markPromptSaved($trackId);$simulateCrash('prompt_saved_at');
  $stmt=$mysqli->prepare('SELECT plan_saved_at,prompt_saved_at,lyrics_saved_at FROM music_ai_tracks WHERE id=?');$stmt->bind_param('i',$trackId);$stmt->execute();$saved=$stmt->get_result()->fetch_assoc();$stmt->close();check($saved['plan_saved_at']&&$saved['prompt_saved_at']&&$saved['lyrics_saved_at'],'Plano, prompt e letra são checkpoints persistentes');
  $columns=['audio_generated_at','audio_validated_at','audio_uploaded_at','cover_generated_at','cover_uploaded_at'];foreach($columns as $index=>$column){$service->markCheckpoint($trackId,$column,'Teste de checkpoint',35+$index*10,['checkpoint'=>$column]);$mysqli->query("UPDATE music_ai_jobs SET status='PROCESSING',locked_by='crashed-test',started_at=DATE_SUB(NOW(),INTERVAL 30 MINUTE),heartbeat_at=DATE_SUB(NOW(),INTERVAL 30 MINUTE),attempts=1 WHERE id=".(int)$jobA);check($queue->recoverStale(5)>=1,"Queda após {$column} recupera o job");$stmt=$mysqli->prepare("SELECT {$column} checkpoint FROM music_ai_tracks WHERE id=?");$stmt->bind_param('i',$trackId);$stmt->execute();check((bool)$stmt->get_result()->fetch_assoc()['checkpoint'],"Retomada preserva {$column}");$stmt->close();}
  $publishBlocked=false;try{$service->publish($trackId,$ownerA);}catch(MusicPermanentException $e){$publishBlocked=true;}check($publishBlocked,'Publicação incompleta é bloqueada');
  $path='/tmp/musiclite-test';$sha=str_repeat('a',64);$validation='{}';$mimeAudio='audio/mpeg';$mimeCover='image/png';$audio='audio.mp3';$cover='cover.png';$typeA='AUDIO';$typeC='COVER';
  $stmt=$mysqli->prepare('INSERT INTO music_ai_media(track_id,user_id,media_type,original_filename,stored_filename,mime_type,file_size,storage_path,checksum_sha256,validation_json)VALUES(?,?,?,?,?,?,1,?,?,?)');$stmt->bind_param('iisssssss',$trackId,$ownerA,$typeA,$audio,$audio,$mimeAudio,$path,$sha,$validation);$stmt->execute();$audioId=(int)$stmt->insert_id;$stmt->bind_param('iisssssss',$trackId,$ownerA,$typeC,$cover,$cover,$mimeCover,$path,$sha,$validation);$stmt->execute();$coverId=(int)$stmt->insert_id;$stmt->close();
  $stmt=$mysqli->prepare("UPDATE music_ai_tracks SET status='COMPLETED',audio_media_id=?,cover_media_id=? WHERE id=?");$stmt->bind_param('iii',$audioId,$coverId,$trackId);$stmt->execute();$stmt->close();$service->publish($trackId,$ownerA);
  $stmt=$mysqli->prepare("SELECT id FROM music_ai_tracks WHERE id=? AND status='COMPLETED' AND is_published=1 AND audio_media_id IS NOT NULL AND cover_media_id IS NOT NULL");$stmt->bind_param('i',$trackId);$stmt->execute();check((bool)$stmt->get_result()->fetch_assoc(),'Publicação exige áudio, capa e conclusão');$stmt->close();
  $simulateCrash('publication_completed_at');$stmt=$mysqli->prepare('SELECT publication_completed_at FROM music_ai_tracks WHERE id=?');$stmt->bind_param('i',$trackId);$stmt->execute();check((bool)$stmt->get_result()->fetch_assoc()['publication_completed_at'],'Queda após publicação preserva o checkpoint final');$stmt->close();
  $stmt=$mysqli->prepare("UPDATE music_ai_tracks SET title='Ataque' WHERE id=? AND owner_user_id=?");$stmt->bind_param('ii',$trackId,$ownerB);$stmt->execute();check($stmt->affected_rows===0,'Outro usuário não edita a música');$stmt->close();
  $runKey='daily:2099-01-01';$stmt=$mysqli->prepare("INSERT INTO music_ai_agent_runs(run_key,trigger_type,scheduled_for,owner_user_id,track_id)VALUES(?,'DAILY','2099-01-01',?,?)");$stmt->bind_param('sii',$runKey,$ownerA,$trackId);$stmt->execute();$runId=(int)$stmt->insert_id;$duplicate=false;try{$stmt->execute();}catch(mysqli_sql_exception $e){$duplicate=(int)$e->getCode()===1062;}$stmt->close();check($duplicate,'Chave daily:AAAA-MM-DD impede duas músicas diárias');
  (new DailyMusicAgentService($mysqli))->reconcile();$stmt=$mysqli->prepare('SELECT status FROM music_ai_agent_runs WHERE id=?');$stmt->bind_param('i',$runId);$stmt->execute();check(($stmt->get_result()->fetch_assoc()['status']??'')==='COMPLETED','Reconciliador conclui execução editorial publicada');$stmt->close();
  $requestId='123e4567-e89b-42d3-a456-426614174000';$requestType='AUDIO';$stmt=$mysqli->prepare('INSERT INTO music_ai_ingest_requests(request_id,track_id,media_type)VALUES(?,?,?)');$stmt->bind_param('sis',$requestId,$trackId,$requestType);$stmt->execute();$replayBlocked=false;try{$stmt->execute();}catch(mysqli_sql_exception $e){$replayBlocked=(int)$e->getCode()===1062;}$stmt->close();check($replayBlocked,'Request ID único bloqueia replay de ingestão');
  $queue->heartbeat('test-music-worker','PROCESSING',$jobA,$trackId,'Teste',[]);$mysqli->query("UPDATE music_ai_jobs SET status='PROCESSING',locked_by='test-music-worker',heartbeat_at=NOW() WHERE id=".(int)$jobA);$queue->heartbeat('test-music-worker','STOPPED');check($queue->recoverStoppedWorkers()>=1,'Job de worker encerrado é recuperado imediatamente');
  $mysqli->rollback();
}catch(Throwable $e){$mysqli->rollback();echo'[ERRO] '.$e->getMessage()."\n";$failed++;}
echo"\nResultado: {$passed} aprovados, {$failed} falhas.\n";exit($failed?1:0);
